version: '2'

services:

  orderer.reliance-network.com:
    container_name: orderer.reliance-network.com
    image: hyperledger/fabric-orderer:latest #x86_64-1.0.0-rc1
    environment:
      #- ORDERER_GENERAL_LOGLEVEL=INFO
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      #- ORDERER_GENERAL_LISTENADDRESS=orderer.reliance-network.com:7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # Enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      #- ORDERER_GENERAL_TLS_ENABLED=false #Enabling ca as a seperate entity
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/reliance-network.com/orderers/orderer.reliance-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/reliance-network.com/orderers/orderer.reliance-network.com/tls/:/var/hyperledger/orderer/tls
    #- orderer.reliance-network.com:/var/hyperledger/production/orderer
    - ../crypto-config/ordererOrganizations/reliance-network.com:/var/hyperledger/production/orderer 
    ports:
      - 7050:7050

  peer0.infrastructure.reliance-network.com:
    container_name: peer0.infrastructure.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.infrastructure.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.infrastructure.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.infrastructure.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.infrastructure.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=infrastructureMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/infrastructure.reliance-network.com/peers/peer0.infrastructure.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/infrastructure.reliance-network.com/peers/peer0.infrastructure.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.infrastructure.reliance-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.infrastructure.reliance-network.com:
    container_name: peer1.infrastructure.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.infrastructure.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.infrastructure.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.infrastructure.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.infrastructure.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=infrastructureMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/infrastructure.reliance-network.com/peers/peer1.infrastructure.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/infrastructure.reliance-network.com/peers/peer1.infrastructure.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.infrastructure.reliance-network.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.power.reliance-network.com:
    container_name: peer0.power.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.power.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.power.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.power.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.power.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=powerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/power.reliance-network.com/peers/peer0.power.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/power.reliance-network.com/peers/peer0.power.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.power.reliance-network.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.power.reliance-network.com:
    container_name: peer1.power.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.power.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.power.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.power.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.power.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=powerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/power.reliance-network.com/peers/peer1.power.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/power.reliance-network.com/peers/peer1.power.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.power.reliance-network.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.communication.reliance-network.com:
    container_name: peer0.communication.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.communication.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.communication.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.communication.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.communication.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=communicationMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/communication.reliance-network.com/peers/peer0.communication.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/communication.reliance-network.com/peers/peer0.communication.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.communication.reliance-network.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.communication.reliance-network.com:
    container_name: peer1.communication.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.communication.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.communication.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.communication.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.communication.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=communicationMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/communication.reliance-network.com/peers/peer1.communication.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/communication.reliance-network.com/peers/peer1.communication.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.communication.reliance-network.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053

  peer0.entertainment.reliance-network.com:
    container_name: peer0.entertainment.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.entertainment.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.entertainment.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.entertainment.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.entertainment.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=entertainmentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/entertainment.reliance-network.com/peers/peer0.entertainment.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/entertainment.reliance-network.com/peers/peer0.entertainment.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.entertainment.reliance-network.com:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053

  peer1.entertainment.reliance-network.com:
    container_name: peer1.entertainment.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.entertainment.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.entertainment.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.entertainment.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.entertainment.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=entertainmentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/entertainment.reliance-network.com/peers/peer1.entertainment.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/entertainment.reliance-network.com/peers/peer1.entertainment.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.entertainment.reliance-network.com:/var/hyperledger/production
    ports:
      - 14051:7051
      - 14053:7053

  peer0.capital.reliance-network.com:
    container_name: peer0.capital.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.capital.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.capital.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.capital.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.capital.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=capitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/capital.reliance-network.com/peers/peer0.capital.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/capital.reliance-network.com/peers/peer0.capital.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.capital.reliance-network.com:/var/hyperledger/production
    ports:
      - 15051:7051
      - 15053:7053

  peer1.capital.reliance-network.com:
    container_name: peer1.capital.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.capital.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.capital.reliance-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.capital.reliance-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.capital.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=capitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/capital.reliance-network.com/peers/peer1.capital.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/capital.reliance-network.com/peers/peer1.capital.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.capital.reliance-network.com:/var/hyperledger/production
    ports:
      - 16051:7051
      - 16053:7053
